# backend/test_docker-compose.yml
services:
  test:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    container_name: lockbox-server
    user: '1000:1000'
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: test
    env_file:
      - ./server/test.env
    depends_on:
      - db_test
      - cache_test
    volumes:
      - ./server:/server:Z
    command: npm run test:watchAll

  db_test:
    image: postgres:17.5-alpine3.21
    restart: always
    container_name: lockbox-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
      POSTGRES_DB: lockbox_dev
      POSTGRES_LOG_MIN_MESSAGES: warning
    tmpfs:
      - /var/lib/postgresql/data

  cache_test:
    image: redis:8.0-alpine3.21
    restart: always
    container_name: lockbox-cache
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass cachepass
    tmpfs:
      - /data
