name: Backend Tests (Docker Compose)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Docker Compose Test Profile
        working-directory: ./backend
        run: |
          docker compose --profile test up --build --abort-on-container-exit --exit-code-from server_test

      - name: Tear down
        if: always()
        working-directory: ./backend
        run: docker compose --profile test down -v
